### ISSUE TITLE
An error occurred while analyzing the dataset (out-of-memory)

### ISSUE THREAD

**Issue by Youssef1313** [dodona-edu/dolos#1328]
I'm analyzing a simple 1.5MB zip file consisting of Java files, but getting out-of-memory.

**Comment by rien** [comment]
Hi @Youssef1313 how many files are you analyzing? How big are they?

Do you get this problem with the web server? Or using the CLI?

**Comment by Youssef1313** [comment]
@rien Using the web server. 1461 Java files.

**Comment by rien** [comment]
I've take a closer look at the logs and it seems like the submissions you want to analyze have multiple files per submission.

We currently don't support grouping files together, so each file would be compared with all the others instead of with other groups. This needs a lot of memory and would give sub-par results.

In the mean time (until #1121 is implemented), you could try concatenating all files that belong to the same submission into one file (if you're using linux: `cat **/*.java > combined.java`).

Let me know if you need more help with this.

**Comment by Youssef1313** [comment]
Great. Thanks!
