### ISSUE TITLE
benchmark results

### ISSUE THREAD

**Issue by ISteampowered** [dodona-edu/dolos#48]
An issue, to aggregate the results and conclusions from the benchmark results.

**Comment by ISteampowered** [comment]
It seems that the curly braces never get matched. I think this is because in the code tokenizer class we only ever use the starting row and don't ever use the rest of the information.

<details>
<summary>screenshot</summary>

Here the blue represents what was matched and the green what one would expect to be matched. Result generated by the benchmark "simple rename".

![noBraces](https://user-images.githubusercontent.com/32019454/64685104-a9252200-d486-11e9-800d-b7dc59564fce.png)


</details>

**Comment by pdawyndt** [comment]
We may consider two changes:

- take into account [start, stop]-ranges instead of starting point only when it comes to mapping hashes to the original source code (may be complicated as we also have a mapping between source code and tokens)
- work with (byte)-offset from the start of the file, instead of line:column locations

**Comment by ISteampowered** [comment]
Both of these need to take into consideration that when a larger declaration that spans multiple lines (a class or function declaration for example) should only be matched if all it's child decelerations are also matched.

**Comment by rien** [comment]
I have created a new issue (#93) for how we want to make our benchmarks available.
