### ISSUE TITLE
Add overview

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#557]
Dolos web interface should display an overview page of the analysis (home page):

- settings
  - programming language
  - number of files
  - k-gram size
  - window size
  - date when analysis was run
- results
  - files that could not be parsed due to syntax errors
  - confirmed cases of plagiarism by manual inspection (# files, # file pairs)

**Comment by rien** [comment]
This page should be the first page shown to users and should contain actionable information.

As main visualization we could show a histogram which can give a quick impression of the similarities. Showing all intersections would be too much because of the quadratic growth, a single datapoint per file would be better. A good candidate is the highest similarity per file.

**Comment by maartenvn** [comment]
Closed by #740
