### ISSUE TITLE
feature request: labels in graph

### ISSUE THREAD

**Issue by eivindflobak** [dodona-edu/dolos#720]
Thank you for making and sharing this very useful application. 

I would like to see labels for each node in the graph, so I can see which code the node represents.

I noticed that I can press the links between nodes and see the diff, but it would be nice to also see which codes represent groups, which are outliers etc. Maybe I'm missing something obvious

Thanks!

**Comment by rien** [comment]
Hi @eivindflobak!

If you want to add a color to the nodes in the graph, you can submit a CSV-file to Dolos with the following format:
```
"filename","labels"
path/to/file1.java,"group1"
path/to/file2.java,"group2"
```
This will color nodes with the same labels in the same color.

Some information in the graph view is currently not shown due to a bug, we will try to release a new version with this fixed as soon as possible.
Other features you request are currently in the pipeline: we're adding clustering and a summarizing view which will help detecting suspicious outliers.
