### ISSUE TITLE
Improve performance of displaying plagiarism graphs including singletons

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#908]
Plagiarism graphs without singletons are displayed immediately. However, as soon as you start toggling the "display singletons" button, all nodes start flying in from the edges of the viewport and only find their final position quite slowly. Find a way to speed up this process.

**Comment by rien** [comment]
This issue is indeed known, but not easily solvable with the current simulation.

One possible solution would be to use [hierarchical clustering](https://en.wikipedia.org/wiki/Hierarchical_clustering) based on the similarity to determine the starting location of nodes. If the initial position of a node is good from the start, we could also minimize a lot of the calculations done in the force simulation, improving performance. This would also allow us to calculate/cache cluster values faster.

However, this requires a complete rework of the current plagiarism graph and cluster code.

**Comment by rien** [comment]
Related to #930

**Comment by rien** [comment]
Yes, indeed.
